version: 2

project_name: poit

builds:
  - main: ./cli/poit
    dir: .
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

brews:
  - name: poit
    repository:
      owner: rowicy
      name: homebrew-tools
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/rowicy/poit"