version: 2

project_name: poit

builds:
  - main: .
    dir: ./cli/poit
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

homebrew_casks:
  - name: poit
    repository:
      owner: rowicy
      name: homebrew-tools
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/rowicy/poit"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poit"]
          end